<?php

namespace Database\Seeders;

use App\Models\Material;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MaterialsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('إنشاء مواد الحضانة باللغة العربية...');

        // الحصول على مستخدم لتعيينه كمنشئ
        $user = User::first();

        // إنشاء مواد الحضانة باللغة العربية
        $kindergartenMaterials = [
            // أدوات الرسم والحرف اليدوية
            [
                'name' => 'أقلام مائية أمان للأطفال',
                'description' => 'أقلام مائية غير سامة لأنشطة الأطفال',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 50,
                'quantity_required' => 30,
                'unit_cost' => 2500,
                'supplier' => 'متجر الأدوات الفنية',
                'storage_location' => 'خزانة الفنون - قسم أ',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ورق رسم عالي الجودة',
                'description' => 'ورق عالي الجودة لأعمال فن الأطفال',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 200,
                'quantity_required' => 150,
                'unit_cost' => 150,
                'supplier' => 'متجر المكتب',
                'storage_location' => 'خزانة الفنون - قسم ب',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'أقلام شمع قابلة للغسل',
                'description' => 'أقلام شمع قابلة للغسل لاستخدام الأطفال',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 40,
                'quantity_required' => 25,
                'unit_cost' => 3000,
                'supplier' => 'لوازم تعليمية',
                'storage_location' => 'درج الفصل',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مقصات أمان للأطفال',
                'description' => 'مقصات آمنة للأطفال لأنشطة الحرف',
                'category' => 'arts_crafts',
                'type' => 'reusable',
                'quantity_available' => 25,
                'quantity_required' => 20,
                'unit_cost' => 2500,
                'supplier' => 'معدات السلامة',
                'storage_location' => 'درج الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ملاصق غراء قابلة للغسل',
                'description' => 'ملاصق غراء قابلة للغسل لأعمال الورق',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 30,
                'quantity_required' => 20,
                'unit_cost' => 800,
                'supplier' => 'متجر المكتب',
                'storage_location' => 'خزانة الفنون - قسم أ',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'أقلام تلوين متنوعة',
                'description' => 'أقلام تلوين متنوعة لتعلم الألوان',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 35,
                'quantity_required' => 25,
                'unit_cost' => 1500,
                'supplier' => 'لوازم تعليمية',
                'storage_location' => 'خزانة الفنون - قسم ج',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ورق كروشيه ملون',
                'description' => 'ورق ملون عالي الجودة لمشاريع الحرف',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 60,
                'quantity_required' => 40,
                'unit_cost' => 1200,
                'supplier' => 'متجر المواد الورقية',
                'storage_location' => 'خزانة الفنون - قسم د',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'طين صناعي مرن',
                'description' => 'طين صناعي قابل للتشكيل للأطفال',
                'category' => 'arts_crafts',
                'type' => 'consumable',
                'quantity_available' => 20,
                'quantity_required' => 15,
                'unit_cost' => 1800,
                'supplier' => 'لوازم فنية',
                'storage_location' => 'خزانة الفنون - قسم هـ',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'فرش تلوين ناعمة',
                'description' => 'فرش ناعمة لتعلم الرسم والتلوين',
                'category' => 'arts_crafts',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 1200,
                'supplier' => 'لوازم فنية',
                'storage_location' => 'خزانة الفنون - قسم و',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ممحاة ملونة',
                'description' => 'ممحاة ملونة لتصحيح الأخطاء',
                'category' => 'arts_crafts',
                'type' => 'reusable',
                'quantity_available' => 25,
                'quantity_required' => 20,
                'unit_cost' => 300,
                'supplier' => 'لوازم مكتبية',
                'storage_location' => 'خزانة الفنون - قسم ز',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // الألعاب التعليمية
            [
                'name' => 'مكعبات بناء خشبية',
                'description' => 'مكعبات بناء خشبية لتعلم القياس والمساحة',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 10,
                'unit_cost' => 15000,
                'supplier' => 'شركة الألعاب التعليمية',
                'storage_location' => 'رف منطقة اللعب',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مربع تصنيف الأشكال',
                'description' => 'لعبة تصنيف الأشكال لتطوير الإدراك المعرفي',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 8,
                'unit_cost' => 8000,
                'supplier' => 'ألعاب تطوير العقل',
                'storage_location' => 'صندوق ألعاب منطقة اللعب',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'bear تعلم العد',
                'description' => 'bear ملونة لأعمال الرياضيات',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 6000,
                'supplier' => 'تعلم الرياضيات',
                'storage_location' => 'زاوية الرياضيات',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'الألغاز التعليمية',
                'description' => 'ألغاز مناسبة للعمر لحل المشكلات',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 20,
                'quantity_required' => 15,
                'unit_cost' => 4000,
                'supplier' => 'مصنعي الألغاز',
                'storage_location' => 'رف المنطقة الهادئة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'عداد خشبي للحساب',
                'description' => 'عداد خشبي لتعليم العد والحساب',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 7000,
                'supplier' => 'أدوات تعليمية',
                'storage_location' => 'زاوية الرياضيات',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'أكوام تعليمية للكلمات',
                'description' => 'أكوام تعليمية لتعلم القراءة',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 5000,
                'supplier' => 'اللغة العربية للصغار',
                'storage_location' => 'زاوية القراءة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'لعبة تعلم الحروف العربية',
                'description' => 'لعبة تفاعلية لتعلم الحروف العربية',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 12000,
                'supplier' => 'التعليم الإسلامي',
                'storage_location' => 'زاوية اللغة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'لعبة تعلم الأرقام',
                'description' => 'لعبة تعليمية لتعلم الأرقام من 1 إلى 10',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 10,
                'unit_cost' => 9000,
                'supplier' => 'الرياضيات للأطفال',
                'storage_location' => 'زاوية الرياضيات',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'لعبة الألوان والأشكال',
                'description' => 'لعبة تساعد الأطفال على تمييز الألوان والأشكال',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 14,
                'quantity_required' => 12,
                'unit_cost' => 6500,
                'supplier' => 'التعلم المبكر',
                'storage_location' => 'منطقة الألعاب',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'لعبة التعرف على الحيوانات',
                'description' => 'لعبة تعليمية لتعلم أسماء الحيوانات وصوتها',
                'category' => 'educational_toys',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 10000,
                'supplier' => 'التعلم من خلال اللعب',
                'storage_location' => 'منطقة الألعاب',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // الكتب ومواد القراءة
            [
                'name' => 'كتب صور للأطفال',
                'description' => 'كتب صور مناسبة للعمر وقت القصة',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 60,
                'quantity_required' => 50,
                'unit_cost' => 3500,
                'supplier' => 'دار النشر',
                'storage_location' => 'زاوية المكتبة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'بطاقات تعلم الحروف العربية',
                'description' => 'بطاقات الحروف الأبجدية لتعلم التعرف على الحروف',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 2500,
                'supplier' => 'مواد تعليمية',
                'storage_location' => 'زاوية القراءة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'بطاقات الصوتيات العربية',
                'description' => 'بطاقات الصوتيات لتعلم الأصوات العربية',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 2000,
                'supplier' => 'أدوات تعلم القراءة',
                'storage_location' => 'مركز الأدبية',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'قصص تفاعلية للأطفال',
                'description' => 'قصص تفاعلية لتشجيع القراءة',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 25,
                'quantity_required' => 20,
                'unit_cost' => 4500,
                'supplier' => 'القصص العربية',
                'storage_location' => 'زاوية القصة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'القرآن الكريم للأطفال',
                'description' => 'نسخ مبسطة من القرآن الكريم للأطفال',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 10,
                'unit_cost' => 3000,
                'supplier' => 'مكتبة الأديان',
                'storage_location' => 'زاوية التربية الإسلامية',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كتاب تعلم الصلاة',
                'description' => 'كتاب تعليمي لتعليم الصلاة للأطفال',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 2800,
                'supplier' => 'الكتب الإسلامية',
                'storage_location' => 'زاوية التربية الإسلامية',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كتاب تعلم الأذكار',
                'description' => 'كتاب تعليمي للأذكار اليومية',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 2200,
                'supplier' => 'الكتب الإسلامية',
                'storage_location' => 'زاوية التربية الإسلامية',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كتاب قصص الأنبياء',
                'description' => 'قصص مبسطة لقصص الأنبياء',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 10,
                'unit_cost' => 3200,
                'supplier' => 'الكتب الإسلامية',
                'storage_location' => 'زاوية التربية الإسلامية',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كتاب قواعد اللغة العربية',
                'description' => 'كتاب مبسط لقواعد اللغة العربية',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 4000,
                'supplier' => 'الكتب اللغوية',
                'storage_location' => 'زاوية اللغة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كتاب التعبير والكتابة',
                'description' => 'كتاب تدريب على التعبير والكتابة',
                'category' => 'reading_materials',
                'type' => 'reusable',
                'quantity_available' => 20,
                'quantity_required' => 18,
                'unit_cost' => 2500,
                'supplier' => 'الكتب التعليمية',
                'storage_location' => 'زاوية اللغة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // الموسيقى والحركة
            [
                'name' => 'آلات موسيقية للأطفال',
                'description' => 'آلات موسيقية بحجم الأطفال',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 10000,
                'supplier' => 'معدات الموسيقى',
                'storage_location' => 'زاوية الموسيقى',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'أوشحة رقص خفيفة',
                'description' => 'أوشحة خفيفة لأنشطة الحركة',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 20,
                'quantity_required' => 15,
                'unit_cost' => 1500,
                'supplier' => 'معدات الحركة',
                'storage_location' => 'منطقة الرقص',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'نظام صوت صغير للفصل',
                'description' => 'نظام صوت صغير للفصل',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 3,
                'unit_cost' => 25000,
                'supplier' => 'معدات الصوت',
                'storage_location' => 'خزانة الوسائط',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مكبر صوت لموسيقى الأطفال',
                'description' => 'مكبر صوت خاص بأغاني الأطفال',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 5,
                'quantity_required' => 4,
                'unit_cost' => 8000,
                'supplier' => 'معدات الصوت',
                'storage_location' => 'منطقة الموسيقى',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ميكروفون للأطفال',
                'description' => 'ميكروفون صغير مناسب لصوت الأطفال',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 4,
                'quantity_required' => 3,
                'unit_cost' => 5000,
                'supplier' => 'معدات الصوت',
                'storage_location' => 'منطقة العروض',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كاسيت أغاني الأطفال',
                'description' => 'كاسيت يحتوي على أغاني تعليمية للأطفال',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 2000,
                'supplier' => 'الموسيقى التعليمية',
                'storage_location' => 'خزانة الوسائط',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كروت تعليمية موسيقية',
                'description' => 'كروت لتعليم الأصوات الموسيقية',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 10,
                'unit_cost' => 3500,
                'supplier' => 'الموسيقى التعليمية',
                'storage_location' => 'منطقة الموسيقى',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كروت تعليمية للأصوات',
                'description' => 'كروت تعليمية للأصوات الطبيعية والحيوانات',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 2800,
                'supplier' => 'الموسيقى التعليمية',
                'storage_location' => 'منطقة التعلم',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'بطة مطاطية',
                'description' => 'بطة مطاطية للألعاب الصوتية',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 1200,
                'supplier' => 'ألعاب الأطفال',
                'storage_location' => 'منطقة الألعاب',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كرة الصوت',
                'description' => 'كرة صوتية لألعاب الحركة والصوت',
                'category' => 'music_movement',
                'type' => 'reusable',
                'quantity_available' => 6,
                'quantity_required' => 5,
                'unit_cost' => 3500,
                'supplier' => 'ألعاب الحركة',
                'storage_location' => 'منطقة الألعاب',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // مواد التعلم الرقمي
            [
                'name' => 'تراخيص تطبيقات التعلم',
                'description' => 'تطبيقات تعليمية للأجهزة اللوحية',
                'category' => 'digital_learning',
                'type' => 'digital',
                'quantity_available' => 10,
                'quantity_required' => 10,
                'unit_cost' => 15000,
                'supplier' => 'مزود البرمجيات',
                'storage_location' => 'مكتبة رقمية',
                'is_consumable' => false,
                'is_digital' => true,
                'is_active' => true,
            ],
            [
                'name' => 'محتوى السبورة التفاعلية',
                'description' => 'محتوى تعليمي للسبورات التفاعلية',
                'category' => 'digital_learning',
                'type' => 'digital',
                'quantity_available' => 5,
                'quantity_required' => 5,
                'unit_cost' => 50000,
                'supplier' => 'برمجيات التعليم',
                'storage_location' => 'الخادم',
                'is_consumable' => false,
                'is_digital' => true,
                'is_active' => true,
            ],
            [
                'name' => 'جهاز لوحي تعليمي',
                'description' => 'جهاز لوحي مخصص للتعلم التفاعلي',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 45000,
                'supplier' => 'الأجهزة التعليمية',
                'storage_location' => 'منطقة التعلم الرقمي',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'سبورة تفاعلية',
                'description' => 'سبورة تفاعلية لعرض المحتوى التعليمي',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 2,
                'unit_cost' => 150000,
                'supplier' => 'معدات التعليم',
                'storage_location' => 'غرفة الأنشطة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كاميرا رقمية للأطفال',
                'description' => 'كاميرا صغيرة مناسبة لاستخدام الأطفال',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 4,
                'quantity_required' => 3,
                'unit_cost' => 18000,
                'supplier' => 'معدات التصوير',
                'storage_location' => 'منطقة الأنشطة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ميكروفون رقمي',
                'description' => 'ميكروفون رقمي لتسجيل أصوات الأطفال',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 2,
                'unit_cost' => 8000,
                'supplier' => 'معدات الصوت',
                'storage_location' => 'منطقة الأنشطة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'سماعات رأس للأطفال',
                'description' => 'سماعات مخصصة لاستخدام الأطفال',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 10,
                'unit_cost' => 4500,
                'supplier' => 'معدات الصوت',
                'storage_location' => 'منطقة التعلم الرقمي',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ماسح ضوئي للأطفال',
                'description' => 'ماسح ضوئي صغير لمشاريع الأطفال',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 2,
                'quantity_required' => 2,
                'unit_cost' => 25000,
                'supplier' => 'معدات المكتب',
                'storage_location' => 'منطقة التعلم الرقمي',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'طابعة تعليمية',
                'description' => 'طابعة لطباعة مشاريع الأطفال',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 2,
                'quantity_required' => 2,
                'unit_cost' => 35000,
                'supplier' => 'معدات المكتب',
                'storage_location' => 'منطقة الأنشطة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'لوحة رسم رقمية',
                'description' => 'لوحة رسم رقمية للأطفال',
                'category' => 'digital_learning',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 2,
                'unit_cost' => 28000,
                'supplier' => 'معدات التصوير',
                'storage_location' => 'منطقة الفنون',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // الأثاث والتجهيزات
            [
                'name' => 'طاولات الأطفال',
                'description' => 'طاولات بارتفاع مناسب للأطفال',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 12,
                'unit_cost' => 20000,
                'supplier' => 'أثاث المدرسة',
                'storage_location' => 'غرفة الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كراسي الأطفال',
                'description' => 'كراسي بتصميم مناسب للأطفال',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 48,
                'quantity_required' => 48,
                'unit_cost' => 5000,
                'supplier' => 'أثاث المدرسة',
                'storage_location' => 'غرفة الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'رفوف التخزين للأطفال',
                'description' => 'رفوف تخزين متعددة الاستخدامات',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 8,
                'unit_cost' => 18000,
                'supplier' => 'أثاث التخزين',
                'storage_location' => 'جميع أنحاء الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'أريكة صغيرة',
                'description' => 'أريكة صغيرة لمنطقة الراحة',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 4,
                'quantity_required' => 3,
                'unit_cost' => 25000,
                'supplier' => 'أثاث المدرسة',
                'storage_location' => 'منطقة الراحة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'وسائد قراءة',
                'description' => 'وسائد مريحة لوقت القراءة',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 12,
                'quantity_required' => 10,
                'unit_cost' => 3000,
                'supplier' => 'أثاث المدرسة',
                'storage_location' => 'زاوية المكتبة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'سجادة الأنشطة',
                'description' => 'سجادة كبيرة لأنشطة المجموعة',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 6,
                'quantity_required' => 5,
                'unit_cost' => 8000,
                'supplier' => 'أثاث المدرسة',
                'storage_location' => 'منطقة الأنشطة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مكتب المعلم',
                'description' => 'مكتب معلم الحضانة',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 4,
                'quantity_required' => 4,
                'unit_cost' => 35000,
                'supplier' => 'أثاث المدرسة',
                'storage_location' => 'غرفة الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'خزانة معلقة',
                'description' => 'خزانة لتخزين الألعاب والمواد',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 15000,
                'supplier' => 'أثاث التخزين',
                'storage_location' => 'غرفة الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'منضدة نشاط',
                'description' => 'منضدة مخصصة لأنشطة الحرف اليدوية',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 3,
                'unit_cost' => 22000,
                'supplier' => 'أثاث الأنشطة',
                'storage_location' => 'منطقة الحرف',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'منطقة نوم للأطفال',
                'description' => 'منطقة نوم مريحة للأطفال',
                'category' => 'furniture',
                'type' => 'reusable',
                'quantity_available' => 5,
                'quantity_required' => 4,
                'unit_cost' => 30000,
                'supplier' => 'أثاث النوم',
                'storage_location' => 'منطقة الراحة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // مواد النظافة والصحة
            [
                'name' => 'معقم اليدين للأطفال',
                'description' => 'معقم يدين خفيف للأطفال والموظفين',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 25,
                'quantity_required' => 20,
                'unit_cost' => 2000,
                'supplier' => 'الصيدلية',
                'storage_location' => 'خزانة الصحة',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مناديل ورقية',
                'description' => 'مناديل ورقية للاستخدام اليومي',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 40,
                'quantity_required' => 30,
                'unit_cost' => 800,
                'supplier' => 'المتجر المحلي',
                'storage_location' => 'خزانة الصحة',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'أقنعة وجه قماشية',
                'description' => 'أقنعة وجه قماشية للأطفال',
                'category' => 'hygiene',
                'type' => 'reusable',
                'quantity_available' => 50,
                'quantity_required' => 45,
                'unit_cost' => 500,
                'supplier' => 'المنزل',
                'storage_location' => 'خزانة الصحة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'صابون سائل للأطفال',
                'description' => 'صابون سائل خفيف لغسيل أيدي الأطفال',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 20,
                'quantity_required' => 15,
                'unit_cost' => 1500,
                'supplier' => 'الصيدلية',
                'storage_location' => 'خزانة الصحة',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'فوط ماء للأطفال',
                'description' => 'فوط ماء ناعمة لتنظيف الأطفال',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 30,
                'quantity_required' => 25,
                'unit_cost' => 1000,
                'supplier' => 'المتجر المحلي',
                'storage_location' => 'خزانة الصحة',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مطهر سطحي',
                'description' => 'مطهر سطحي لتنظيف الأسطح',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 2500,
                'supplier' => 'الصيدلية',
                'storage_location' => 'خزانة التنظيف',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'قفازات نitrile',
                'description' => 'قفازات للاستخدام أثناء التنظيف',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 800,
                'supplier' => 'الصيدلية',
                'storage_location' => 'خزانة التنظيف',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'م thermometer',
                'description' => 'مقياس حرارة للأطفال',
                'category' => 'hygiene',
                'type' => 'reusable',
                'quantity_available' => 5,
                'quantity_required' => 4,
                'unit_cost' => 3000,
                'supplier' => 'الصيدلية',
                'storage_location' => 'خزانة الصحة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'كيس طبي صغير',
                'description' => 'كيس طبي لحمل الأدوية الأساسية',
                'category' => 'hygiene',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 3,
                'unit_cost' => 4000,
                'supplier' => 'الصيدلية',
                'storage_location' => 'مكتب الإدارة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مطهر لليدين',
                'description' => 'مطهر لليدين بدون ماء',
                'category' => 'hygiene',
                'type' => 'consumable',
                'quantity_available' => 25,
                'quantity_required' => 20,
                'unit_cost' => 1800,
                'supplier' => 'الصيدلية',
                'storage_location' => 'مختلف الأماكن',
                'is_consumable' => true,
                'is_digital' => false,
                'is_active' => true,
            ],
            
            // مواد الطوارئ
            [
                'name' => 'حقيبة الإسعاف الأولي',
                'description' => 'حقيبة إسعاف أولي متكاملة',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 3,
                'quantity_required' => 3,
                'unit_cost' => 15000,
                'supplier' => 'الصيدلية',
                'storage_location' => 'مكتب الإدارة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'بطانيات الطوارئ',
                'description' => 'بطانيات خفيفة لحالات الطوارئ',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 3000,
                'supplier' => 'المتجر المحلي',
                'storage_location' => 'خزانة الطوارئ',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'صافرة الطوارئ',
                'description' => 'صافرة لجمع الأطفال في حالات الطوارئ',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 6,
                'quantity_required' => 5,
                'unit_cost' => 1200,
                'supplier' => 'معدات الطوارئ',
                'storage_location' => 'مكاتب المعلمين',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مكبر صوت للطوارئ',
                'description' => 'مكبر صوت لنقل التعليمات في حالات الطوارئ',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 2,
                'quantity_required' => 2,
                'unit_cost' => 18000,
                'supplier' => 'معدات الطوارئ',
                'storage_location' => 'مكتب الإدارة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'إضاءة طوارئ',
                'description' => 'إضاءة تعمل عند انقطاع الكهرباء',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 8,
                'quantity_required' => 6,
                'unit_cost' => 5000,
                'supplier' => 'معدات الطوارئ',
                'storage_location' => 'مختلف الغرف',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'خوذة الأمان',
                'description' => 'خوذة لحماية الأطفال في حالات الطوارئ',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 15,
                'quantity_required' => 12,
                'unit_cost' => 2500,
                'supplier' => 'معدات الأمان',
                'storage_location' => 'خزانة الطوارئ',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'بطانية إنقاذ',
                'description' => 'بطانية إنقاذ لحماية الأطفال',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 10,
                'quantity_required' => 8,
                'unit_cost' => 4000,
                'supplier' => 'معدات الإنقاذ',
                'storage_location' => 'خزانة الطوارئ',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'ماسح ضوئي للكشف عن الحمى',
                'description' => 'ماسح ضوئي للكشف عن الحمى بسرعة',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 2,
                'quantity_required' => 2,
                'unit_cost' => 25000,
                'supplier' => 'معدات الصحة',
                'storage_location' => 'مكتب الإدارة',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'سجادة إخلاء',
                'description' => 'سجادة لمساعدة الأطفال في الإخلاء',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 4,
                'quantity_required' => 3,
                'unit_cost' => 8000,
                'supplier' => 'معدات الطوارئ',
                'storage_location' => 'غرف الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
            [
                'name' => 'مخطط الإخلاء',
                'description' => 'مخطط مفصل لإخلاء الأطفال',
                'category' => 'emergency',
                'type' => 'reusable',
                'quantity_available' => 6,
                'quantity_required' => 6,
                'unit_cost' => 1500,
                'supplier' => 'خدمات الطوارئ',
                'storage_location' => 'غرف الفصل',
                'is_consumable' => false,
                'is_digital' => false,
                'is_active' => true,
            ],
        ];

        foreach ($kindergartenMaterials as $materialData) {
            Material::create(array_merge($materialData, [
                'created_by' => $user ? $user->id : 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }

        $this->command->info('تم إنشاء ' . count($kindergartenMaterials) . ' مادة حضانة باللغة العربية.');
    }
}