<?php

return [
    'title' => 'Classes',
    'add_new' => 'Add New Class',
    'edit' => 'Edit Class',
    'list' => 'Classes List',
    'show' => 'View Class',
    'fields' => [
        'name' => 'Name',
        'code' => 'Code',
        'description' => 'Description',
        'teacher_id' => 'Teacher Id',
        'age_group' => 'Age Group',
        'capacity' => 'Capacity',
        'current_students' => 'Current Students',
        'start_time' => 'Start Time',
        'end_time' => 'End Time',
        'room_number' => 'Room Number',
        'monthly_fee' => 'Monthly Fee',
        'is_active' => 'Is Active',
        'grade_level_id' => 'Grade Level',
        'schedule' => 'Schedule',
        'location' => 'Location',
        'start_date' => 'Start Date',
        'end_date' => 'End Date',
        'curriculum' => 'Curriculum',
        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
        'deleted_at' => 'Deleted At',
    ],
    'actions' => [
        'save' => 'Save',
        'cancel' => 'Cancel',
        'update' => 'Update',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'confirm_delete' => 'Are you sure?',
        'archive' => 'Archive',
    ],
    'messages' => [
        'created' => 'Class created successfully.',
        'updated' => 'Class updated successfully.',
        'deleted' => 'Class deleted successfully.',
        'archived' => 'Class archived successfully.',
    ],
    'placeholders' => [
        'name' => 'Enter class name',
        'code' => 'Enter class code',
        'description' => 'Enter class description',
        'capacity' => 'Enter capacity',
        'current_students' => 'Enter current students',
        'room_number' => 'Enter room number',
        'monthly_fee' => 'Enter monthly fee',
        'schedule' => 'Enter class schedule',
        'location' => 'Enter class location',
    ],
    'age_groups' => [
        'toddlers' => 'Toddlers (1-2 years)',
        'preschool' => 'Preschool (3-4 years)',
        'pre_k' => 'Pre-K (4-5 years)',
        'kindergarten' => 'Kindergarten (5-6 years)',
    ],
    'classes' => [
        'messages' => [
            'retrieved' => 'Classes retrieved successfully',
        ],
        'fields' => [
            'grade_id' => 'Grade',
        ],
    ],
];
