<?php

return [
    'title' => 'Financial Reports',
    'add_new' => 'Add New Financial Report',
    'edit' => 'Edit Financial Report',
    'list' => 'Financial Reports List',
    'fields' => [
        'name' => 'Name',
    ],
    'actions' => [
        'save' => 'Save',
        'cancel' => 'Cancel',
        'update' => 'Update',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'confirm_delete' => 'Are you sure?',
    ],
    'messages' => [
        'created' => 'Record created successfully.',
        'updated' => 'Record updated successfully.',
        'deleted' => 'Record deleted successfully.',
    ],
    'reports' => [
        'messages' => [
            'retrieved' => '',
        ],
    ],
    'financial-reports' => [
        'messages' => [
            'created' => 'Financial report created successfully',
            'updated' => 'Financial report updated successfully',
            'deleted' => 'Financial report deleted successfully',
        ],
        'fields' => [
            'report_type' => 'Report Type',
            'period_start' => 'Period Start',
            'period_end' => 'Period End',
            'generated_at' => 'Generated At',
            'generated_by' => 'Generated By',
        ],
        'title' => 'Financial Reports',
        'add_new' => 'Add New Financial Report',
        'edit' => 'Edit Financial Report',
        'list' => 'Financial Reports List',
        'show' => 'Show Financial Report',
    ],
];
