<?php

return [
    'title' => 'الفصول',
    'add_new' => 'إضافة فصل جديد',
    'edit' => 'تعديل فصل',
    'list' => 'قائمة الفصول',
    'show' => 'عرض فصل',
    'fields' => [
        'name' => 'الاسم',
        'code' => 'الرمز',
        'description' => 'الوصف',
        'teacher_id' => 'معرّف المعلم',
        'age_group' => 'مجموعة العمر',
        'capacity' => 'السعة',
        'current_students' => 'الطلاب الحاليون',
        'start_time' => 'وقت البدء',
        'end_time' => 'وقت الانتهاء',
        'room_number' => 'رقم الغرفة',
        'monthly_fee' => 'الرسوم الشهرية',
        'is_active' => 'نشط',
        'grade_level_id' => 'المستوى الدراسي',
        'schedule' => 'الجدول',
        'location' => 'الموقع',
        'start_date' => 'تاريخ البدء',
        'end_date' => 'تاريخ الانتهاء',
        'curriculum' => 'المنهاج',
        'created_at' => 'تاريخ الإنشاء',
        'updated_at' => 'تاريخ التعديل',
        'deleted_at' => 'تاريخ الحذف',
    ],
    'actions' => [
        'save' => 'حفظ',
        'cancel' => 'إلغاء',
        'update' => 'تحديث',
        'edit' => 'تعديل',
        'delete' => 'حذف',
        'confirm_delete' => 'هل أنت متأكد؟',
        'archive' => 'أرشفة',
    ],
    'messages' => [
        'created' => 'تم إنشاء الفصل بنجاح.',
        'updated' => 'تم تحديث الفصل بنجاح.',
        'deleted' => 'تم حذف الفصل بنجاح.',
        'archived' => 'تم أرشفة الفصل بنجاح.',
    ],
    'placeholders' => [
        'name' => 'أدخل اسم الفصل',
        'code' => 'أدخل رمز الفصل',
        'description' => 'أدخل وصف الفصل',
        'capacity' => 'أدخل السعة',
        'current_students' => 'أدخل عدد الطلاب الحاليين',
        'room_number' => 'أدخل رقم الغرفة',
        'monthly_fee' => 'أدخل الرسوم الشهرية',
        'schedule' => 'أدخل جدول الفصل',
        'location' => 'أدخل موقع الفصل',
    ],
    'age_groups' => [
        'toddlers' => 'الرضع (1-2 سنة)',
        'preschool' => 'الروضة (3-4 سنوات)',
        'pre_k' => 'قبل الروضة (4-5 سنوات)',
        'kindergarten' => 'الحضانة (5-6 سنوات)',
    ],
    'classes' => [
        'messages' => [
            'retrieved' => 'تم استرجاع الفصول بنجاح',
        ],
        'fields' => [
            'grade_id' => 'الصف',
        ],
    ],
    'Classes' => [
        'add_new' => 'add_new',
        'edit' => 'edit',
        'title' => 'title',
        'list' => 'list',
        'show' => 'show',
    ],
];
